name: Displaying Content based on Previous Workflow File

on: 
  workflow_dispatch:
jobs:
  display-information:
    runs-on: ubuntu-latest
    steps:
      - uses: adityaraj9415/gh-dotnet-webapp/.github/workflows/display-info.yml@master
      - run: echo "${{ steps.publish.contents }}"
      
