name: Displaying Content based on Previous Workflow File

on: 
  workflow_dispatch:
jobs:
  display-information:
    uses: adityaraj9415/gh-dotnet-webapp/.github/workflows/display-info.yml@master
  
      
