name: Publish Dot-Net-Web-App

on:
  workflow_dispatch:
  
  push:
    branches:
    - main
env:
  AZURE-WEBAPP-NAME: gh-dotnet
  AZURE-PACKAGE: "./publish"


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./gh-dotnet-webapp.sln
        
      - name: Build
        run: dotnet build ./gh-dotnet-webapp.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./gh-dotnet-webapp.sln --configuration Release --no-build output '${{ env.AZURE-PACKAGE }}'
        
      - name: Deployment
        uses: actions/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE-WEBAPP-NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ' ${{ env.AZURE-PACKAGE }}'
        
        
        
